"""empty message

Revision ID: 7f40a0108c81
Revises: 023aeb0050c8
Create Date: 2026-04-05 02:18:23.287283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f40a0108c81'
down_revision = '023aeb0050c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicos')
    with op.batch_alter_table('config_sistema', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('chave'))

    op.drop_table('config_sistema')
    with op.batch_alter_table('projetos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_ano'))
        batch_op.drop_index(batch_op.f('idx_categoria'))
        batch_op.drop_index(batch_op.f('idx_slug'))
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.drop_index(batch_op.f('slug'))

    op.drop_table('projetos')
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('slug'))

    op.drop_table('categorias')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('idx_email'))
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.drop_index(batch_op.f('idx_tipo'))

    op.drop_table('usuarios')
    with op.batch_alter_table('logs_sistema', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_acao'))
        batch_op.drop_index(batch_op.f('idx_data'))
        batch_op.drop_index(batch_op.f('idx_usuario'))

    op.drop_table('logs_sistema')
    with op.batch_alter_table('imagens_projetos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_projeto'))

    op.drop_table('imagens_projetos')
    with op.batch_alter_table('cronograma_obra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_obra'))

    op.drop_table('cronograma_obra')
    with op.batch_alter_table('contactos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_data'))
        batch_op.drop_index(batch_op.f('idx_email'))
        batch_op.drop_index(batch_op.f('idx_lido'))

    op.drop_table('contactos')
    with op.batch_alter_table('obras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cliente'))
        batch_op.drop_index(batch_op.f('idx_status'))

    op.drop_table('obras')
    with op.batch_alter_table('etapas_obra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_obra'))
        batch_op.drop_index(batch_op.f('idx_status'))

    op.drop_table('etapas_obra')
    with op.batch_alter_table('sessoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_token'))
        batch_op.drop_index(batch_op.f('idx_usuario'))
        batch_op.drop_index(batch_op.f('token'))

    op.drop_table('sessoes')
    op.drop_table('clientes')
    with op.batch_alter_table('galeria_publica', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_categoria'))

    op.drop_table('galeria_publica')
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_tipo'))

    op.drop_table('documentos')
    with op.batch_alter_table('servicos_detalhes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_servico'))

    op.drop_table('servicos_detalhes')
    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('idx_email'))
        batch_op.create_index(batch_op.f('ix_newsletter_email'), ['email'], unique=True)
        batch_op.drop_column('data_inscricao')
        batch_op.drop_column('ativo')
        batch_op.drop_column('id_inscricao')
        batch_op.drop_column('nome')
        batch_op.drop_column('data_unsubscribe')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_unsubscribe', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
        batch_op.add_column(sa.Column('id_inscricao', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('ativo', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_inscricao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.drop_index(batch_op.f('ix_newsletter_email'))
        batch_op.create_index(batch_op.f('idx_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('id')

    op.create_table('servicos_detalhes',
    sa.Column('id_detalhe', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_servico', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('titulo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('descricao', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('icone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('ordem', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_servico'], ['servicos.id_servico'], name=op.f('servicos_detalhes_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_detalhe'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('servicos_detalhes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_servico'), ['id_servico'], unique=False)

    op.create_table('documentos',
    sa.Column('id_documento', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_obra', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_projeto', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_cliente', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_documento', mysql.ENUM('contrato', 'planta', 'licenca', 'fatura', 'relatorio', 'outro'), server_default=sa.text("'outro'"), nullable=True),
    sa.Column('titulo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('nome_ficheiro', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('url_ficheiro', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('tamanho_ficheiro', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_mime', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('visivel_cliente', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], name=op.f('documentos_ibfk_3'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_obra'], ['obras.id_obra'], name=op.f('documentos_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_projeto'], ['projetos.id_projeto'], name=op.f('documentos_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_documento'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_tipo'), ['tipo_documento'], unique=False)

    op.create_table('galeria_publica',
    sa.Column('id_galeria', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_projeto', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('url_imagem', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('url_thumbnail', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('titulo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('descricao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('categoria', mysql.ENUM('escritorio', 'equipe', 'eventos', 'processo', 'outro'), server_default=sa.text("'outro'"), nullable=True),
    sa.Column('destaque', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('ordem', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_projeto'], ['projetos.id_projeto'], name=op.f('galeria_publica_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_galeria'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('galeria_publica', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_categoria'), ['categoria'], unique=False)

    op.create_table('clientes',
    sa.Column('id_cliente', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nif', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('morada', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('cidade', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), server_default=sa.text("'Luanda'"), nullable=True),
    sa.Column('provincia', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('pais', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), server_default=sa.text("'Angola'"), nullable=True),
    sa.Column('tipo_pessoa', mysql.ENUM('individual', 'empresa'), server_default=sa.text("'individual'"), nullable=True),
    sa.Column('nome_empresa', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=True),
    sa.Column('setor_atividade', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('observacoes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name=op.f('clientes_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_cliente'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sessoes',
    sa.Column('id_sessao', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('ip_acesso', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True),
    sa.Column('user_agent', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_expiracao', mysql.TIMESTAMP(), nullable=False),
    sa.Column('ativa', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name=op.f('sessoes_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_sessao'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sessoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('idx_usuario'), ['id_usuario'], unique=False)
        batch_op.create_index(batch_op.f('idx_token'), ['token'], unique=False)

    op.create_table('etapas_obra',
    sa.Column('id_etapa', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_obra', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('descricao', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('data_inicio_prevista', sa.DATE(), nullable=True),
    sa.Column('data_fim_prevista', sa.DATE(), nullable=True),
    sa.Column('data_inicio_real', sa.DATE(), nullable=True),
    sa.Column('data_fim_real', sa.DATE(), nullable=True),
    sa.Column('progresso', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('status', mysql.ENUM('pendente', 'em_andamento', 'concluida', 'atrasada'), server_default=sa.text("'pendente'"), nullable=True),
    sa.Column('custo_previsto', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('custo_real', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('observacoes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('ordem', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`progresso` between 0 and 100)', name=op.f('etapas_obra_chk_1')),
    sa.ForeignKeyConstraint(['id_obra'], ['obras.id_obra'], name=op.f('etapas_obra_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_etapa'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('etapas_obra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_obra'), ['id_obra'], unique=False)

    op.create_table('obras',
    sa.Column('id_obra', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_projeto', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_cliente', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome_obra', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('descricao', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('localizacao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('valor_contrato', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('data_inicio', sa.DATE(), nullable=True),
    sa.Column('data_prevista_fim', sa.DATE(), nullable=True),
    sa.Column('data_fim_real', sa.DATE(), nullable=True),
    sa.Column('status_obra', mysql.ENUM('nao_iniciada', 'em_preparacao', 'em_execucao', 'parada', 'concluida', 'entregue'), server_default=sa.text("'nao_iniciada'"), nullable=True),
    sa.Column('progresso', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('observacoes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint('(`progresso` between 0 and 100)', name=op.f('obras_chk_1')),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], name=op.f('obras_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_projeto'], ['projetos.id_projeto'], name=op.f('obras_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_obra'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('obras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_status'), ['status_obra'], unique=False)
        batch_op.create_index(batch_op.f('idx_cliente'), ['id_cliente'], unique=False)

    op.create_table('contactos',
    sa.Column('id_contacto', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('telefone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('assunto', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('mensagem', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('ip_origem', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True),
    sa.Column('lido', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('respondido', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('data_resposta', mysql.DATETIME(), nullable=True),
    sa.Column('observacoes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id_contacto'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('contactos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_lido'), ['lido'], unique=False)
        batch_op.create_index(batch_op.f('idx_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_data'), ['data_criacao'], unique=False)

    op.create_table('cronograma_obra',
    sa.Column('id_marco', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_obra', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('titulo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('descricao', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('data_prevista', sa.DATE(), nullable=True),
    sa.Column('data_concluida', sa.DATE(), nullable=True),
    sa.Column('status', mysql.ENUM('pendente', 'concluido', 'atrasado'), server_default=sa.text("'pendente'"), nullable=True),
    sa.Column('concluído', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_obra'], ['obras.id_obra'], name=op.f('cronograma_obra_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_marco'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('cronograma_obra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_obra'), ['id_obra'], unique=False)

    op.create_table('imagens_projetos',
    sa.Column('id_imagem', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_projeto', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url_imagem', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('url_thumbnail', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('titulo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('descricao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('tipo', mysql.ENUM('principal', 'galeria', 'antes', 'depois'), server_default=sa.text("'galeria'"), nullable=True),
    sa.Column('ordem', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_projeto'], ['projetos.id_projeto'], name=op.f('imagens_projetos_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_imagem'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('imagens_projetos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_projeto'), ['id_projeto'], unique=False)

    op.create_table('logs_sistema',
    sa.Column('id_log', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('acao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('modulo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('descricao', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('ip_acesso', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True),
    sa.Column('user_agent', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name=op.f('logs_sistema_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_log'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('logs_sistema', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_usuario'), ['id_usuario'], unique=False)
        batch_op.create_index(batch_op.f('idx_data'), ['data_criacao'], unique=False)
        batch_op.create_index(batch_op.f('idx_acao'), ['acao'], unique=False)

    op.create_table('usuarios',
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('telefone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('tipo_usuario', mysql.ENUM('cliente', 'admin', 'funcionario'), server_default=sa.text("'cliente'"), nullable=True),
    sa.Column('status_conta', mysql.ENUM('ativa', 'inativa', 'pendente', 'bloqueada'), server_default=sa.text("'ativa'"), nullable=True),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('ultimo_login', mysql.DATETIME(), nullable=True),
    sa.Column('token_redefinicao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('token_expiracao', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_tipo'), ['tipo_usuario'], unique=False)
        batch_op.create_index(batch_op.f('idx_status'), ['status_conta'], unique=False)
        batch_op.create_index(batch_op.f('idx_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('categorias',
    sa.Column('id_categoria', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('slug', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('descricao', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('imagem_capa', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('ordem', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('status', mysql.ENUM('ativa', 'inativa'), server_default=sa.text("'ativa'"), nullable=True),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('slug'), ['slug'], unique=True)

    op.create_table('projetos',
    sa.Column('id_projeto', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_categoria', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('titulo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('slug', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('descricao', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('descricao_detalhada', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('localizacao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('cliente_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('area_m2', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('ano_conclusao', mysql.YEAR(), nullable=True),
    sa.Column('status_projeto', mysql.ENUM('em_planeamento', 'em_execucao', 'concluido', 'entregue'), server_default=sa.text("'em_planeamento'"), nullable=True),
    sa.Column('destaque', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('_orçamento', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('data_inicio', sa.DATE(), nullable=True),
    sa.Column('data_conclusao', sa.DATE(), nullable=True),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id_cliente'], name=op.f('projetos_ibfk_2'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id_categoria'], name=op.f('projetos_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_projeto'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('projetos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('idx_status'), ['status_projeto'], unique=False)
        batch_op.create_index(batch_op.f('idx_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('idx_categoria'), ['id_categoria'], unique=False)
        batch_op.create_index(batch_op.f('idx_ano'), ['ano_conclusao'], unique=False)

    op.create_table('config_sistema',
    sa.Column('id_config', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chave', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('valor', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('descricao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id_config'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('config_sistema', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('chave'), ['chave'], unique=True)

    op.create_table('servicos',
    sa.Column('id_servico', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('slug', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('titulo_card', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('descricao_resumida', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('descricao_completa', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('icone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('_resumo', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('status', mysql.ENUM('ativo', 'inativo'), server_default=sa.text("'ativo'"), nullable=True),
    sa.Column('ordem', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id_servico'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
